### ISSUE TITLE
low meter levels displayed

### ISSUE THREAD

**Issue by Shad-Rydalch** [kryops/remote-mixer#1]
https://github.com/kryops/remote-mixer/blob/67fc65765064d37654d5400966c1bc25c3f6f429/backend/src/devices/yamaha-01v96/mapping.ts#L191

I found that the meter levels presented were low, never reaching full scale. Multiplying the message.data by 7 produced favorable results.

outMessage.meters[`ch${channel}`] = message.data[2 * (channel - 1)] * 7

**Comment by kryops** [comment]
Hi @Shad-Rydalch,

thanks for your report! You are right, I must have missed this because in 01v96-remote this was implemented in the frontend rather than the backend: https://github.com/kryops/01v96-remote/blob/master/client/js/main.js#L989

I now used the same implementation here. It suggests that while the meter values can range from 0-32 (we need to convert it to 0-255, which would be a factor of almost 8), it is not a linear scale. I have no idea how I came up with the formula back then, but not being able to find any proper documentation, I guess I must have used trial&error 😅 

Could you check if the change works as expected? How does it compare against your approach of just multiplying the level by 7?
It will be a while before I have access to a 01v96 again to try it out myself unfortunately 😕

**Comment by Shad-Rydalch** [comment]
Hello again,

The convertMeterLevel function inverts the levels as written: "(1 - Math.pow(deviceLevel, 2) / Math.pow(32, 2)) * 255". With no input the meter is at the top, bring the input level up on the mixer input and the meter lowers. Would have expected the level to rise with the increase input. Full input with the peak LED lit sends the meter below the bottom of the meter box all the way to the bottom of the screen. I found that if changed the function formula to "(Math.pow(deviceLevel, 2) / Math.pow(32, 2)) * 255" it works as expected. Using the formula you have matches the meter levels displayed on the mixer better than just multiplying the level by 7.

Thank you!

**Comment by kryops** [comment]
:man_facepalming: of course you are right - in 01v96remote, the meter level was rendered kind of up side down (the meter bar was always rendered in full, but overlayed at the top). I will hopefully fix it this time - thanks for your verification!
